| **Inicio** | **atrás 8** | **Siguiente 10** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./8.Estructuras_de_datos_Conjuntos.ipynb)| [⏩](./10.Funciones_en_Python.ipynb)|

# **9. Estructuras de datos: Tuplas**

## **Introducción a tuplas**

En Python, una tupla es una estructura de datos inmutable que permite almacenar un conjunto ordenado de elementos. A diferencia de las listas, las tuplas no pueden ser modificadas una vez que se han creado, lo que las hace adecuadas para almacenar datos que no deben ser alterados, como coordenadas geográficas, valores constantes o resultados de cálculos complejos.

Para crear una tupla en Python, se utilizan paréntesis `()` y se separan los elementos con comas. Por ejemplo:

In [1]:
mi_tupla = (1, 2, 3, 4)

También se pueden crear tuplas utilizando la función `tuple()`, pasando como argumento un objeto iterable:

In [2]:
otra_tupla = tuple([5, 6, 7, 8])

Las tuplas pueden contener diferentes tipos de datos, como números, cadenas de texto, booleanos, entre otros:

In [3]:
tupla_mixta = (1, "Hola", True)

Una vez que se ha creado una tupla, sus elementos se pueden acceder utilizando un índice numérico. Por ejemplo, para acceder al segundo elemento de la tupla `mi_tupla`, se utiliza el índice `1` (los índices en Python comienzan en `0`):

In [4]:
segundo_elemento = mi_tupla[1]

También es posible acceder a un rango de elementos de una tupla utilizando la sintaxis de rebanado `(slice en inglés)`:

In [5]:
subtupla = mi_tupla[1:3]

Este ejemplo devuelve una tupla que contiene los elementos en los índices `1` y `2` de `mi_tupla`.

Las tuplas también admiten algunas operaciones útiles, como la concatenación `(unión de dos tuplas)`:

In [7]:
tupla_1 = (1, 2, 3)
tupla_2 = (4, 5, 6)
tupla_concatenada = tupla_1 + tupla_2
print(tupla_concatenada)

(1, 2, 3, 4, 5, 6)


Este ejemplo crea una nueva tupla que contiene todos los elementos de `tupla_1` seguidos de todos los elementos de `tupla_2`.

Por último, las tuplas se pueden desempaquetar, lo que significa que se pueden asignar cada uno de los elementos de la tupla a una variable diferente en una sola línea de código:

In [8]:
coordenadas = (10.0, 20.0)
x, y = coordenadas
print(coordenadas)

(10.0, 20.0)


En este ejemplo, se crea una tupla llamada `coordenadas` que contiene dos elementos. Luego, se desempaqueta la tupla y se asigna el primer elemento a la variable `x` y el segundo elemento a la variable `y`. Ahora, `x` contiene `10.0` y `y` contiene `20.0`.

En resumen, las tuplas en Python son estructuras de datos inmutables que permiten almacenar un conjunto ordenado de elementos. Se crean utilizando paréntesis y se separan los elementos con comas. Los elementos de una tupla se pueden acceder utilizando un índice numérico, y las tuplas admiten algunas operaciones útiles como la concatenación y el desempaquetado.

## **Elementos de una tupla**

Los elementos de una tupla en Python pueden ser cualquier tipo de datos, como números, cadenas de texto, booleanos, listas, tuplas, entre otros. La tupla en sí misma es una estructura de datos inmutable, lo que significa que una vez que se crea, no se puede modificar su contenido. Por lo tanto, los elementos de una tupla no pueden ser agregados, eliminados o modificados después de su creación.

Veamos algunos ejemplos de tuplas con diferentes tipos de datos como elementos:

In [9]:
tupla_numeros = (1, 2, 3, 4, 5)
print(tupla_numeros)

tupla_letras = ('a', 'b', 'c', 'd', 'e')
print(tupla_letras)

tupla_booleanos = (True, False, False, True)
print(tupla_booleanos)

tupla_mezclada = ('hola', 3.1416, True, [1,2,3], ('a', 'b', 'c'))
print(tupla_mezclada)

(1, 2, 3, 4, 5)
('a', 'b', 'c', 'd', 'e')
(True, False, False, True)
('hola', 3.1416, True, [1, 2, 3], ('a', 'b', 'c'))


En estos ejemplos, `tupla_numeros` es una tupla que contiene cinco números enteros, `tupla_letras` es una tupla que contiene cinco cadenas de texto, `tupla_booleanos` es una tupla que contiene cuatro valores booleanos y `tupla_mezclada` es una tupla que contiene una mezcla de diferentes tipos de datos, incluyendo una lista y otra tupla.

También es posible crear tuplas anidadas, es decir, tuplas que contienen otras tuplas como elementos. Por ejemplo:

In [10]:
tupla_anidada = ((1,2,3), ('a','b','c'), (True, False, True))
print(tupla_anidada)

((1, 2, 3), ('a', 'b', 'c'), (True, False, True))


En este ejemplo, `tupla_anidada` es una tupla que contiene tres tuplas, cada una con tres elementos. Podemos acceder a los elementos de la tupla anidada utilizando índices múltiples, como en el siguiente ejemplo:

In [11]:
primer_elemento_tupla_anidada = tupla_anidada[0][0]
print(primer_elemento_tupla_anidada)

1


Este ejemplo devuelve el primer elemento de la primera tupla en `tupla_anidada`, que es el número `1`.

En resumen, los elementos de una tupla en Python pueden ser cualquier tipo de datos, incluyendo otros objetos complejos como listas y tuplas. La tupla en sí misma es inmutable, lo que significa que los elementos no pueden ser modificados después de la creación de la tupla.

## **El método unpacking**

El método `unpacking` en Python permite desempacar los elementos de una estructura de datos iterable (como una lista o tupla) en variables individuales, lo que resulta muy útil en varias situaciones, como cuando se necesita asignar varios valores a diferentes variables o cuando se desea iterar sobre los elementos de una estructura de datos de manera más eficiente.

Veamos un ejemplo sencillo de cómo utilizar el método `unpacking` en Python:

In [12]:
numeros = [1, 2, 3]
a, b, c = numeros

print(a) # Output: 1
print(b) # Output: 2
print(c) # Output: 3

1
2
3


En este ejemplo, creamos una lista llamada numeros que contiene tres valores enteros. A continuación, utilizamos el método `unpacking` para desempacar los valores de la lista en tres variables separadas: `a`, `b` y `c`. Después, imprimimos el valor de cada variable en la consola.

También es posible utilizar el método `unpacking` para desempacar los elementos de una tupla. Veamos un ejemplo:

In [13]:
frutas = ('manzana', 'banana', 'kiwi')
fruta1, fruta2, fruta3 = frutas

print(fruta1) # Output: 'manzana'
print(fruta2) # Output: 'banana'
print(fruta3) # Output: 'kiwi'

manzana
banana
kiwi


En este ejemplo, creamos una tupla llamada frutas que contiene tres cadenas de texto. Utilizamos el método `unpacking` para asignar cada cadena de texto a una variable separada (`fruta1`, `fruta2` y `fruta3`). Después, imprimimos el valor de cada variable en la consola.

El método `unpacking` también puede ser utilizado para desempacar los elementos de una estructura de datos iterable dentro de una función. Veamos un ejemplo:

In [16]:
numeros = [1, 2, 3]

def sumar_numeros(a, b, c):
    return a + b + c

resultado = sumar_numeros(*numeros)

print(resultado) # Output: 6

6


En este ejemplo, creamos una función llamada `sumar_numeros` que toma tres argumentos numéricos y devuelve su `suma`. Luego, creamos una lista llamada `numeros` que contiene tres números enteros y utilizamos el método `unpacking` para pasar los valores de la lista como argumentos a la función `sumar_numeros`. Finalmente, almacenamos el resultado de la función en una variable llamada `resultado` y lo imprimimos en la consola.

En resumen, el método `unpacking` en Python es una técnica muy útil para desempacar los elementos de una estructura de datos iterable en variables individuales. Esto puede ser útil en situaciones en las que necesitamos asignar múltiples valores a diferentes variables o iterar de manera eficiente sobre los elementos de una estructura de datos.

## **Concatenación y repetición de tuplas**

La concatenación y repetición de tuplas en Python son dos operaciones que se pueden utilizar para combinar o duplicar tuplas existentes.

La concatenación de tuplas en Python se realiza utilizando el operador de suma `(+)`. Este operador toma dos tuplas y las combina en una nueva tupla que contiene todos los elementos de ambas tuplas. Veamos un ejemplo:

In [17]:
tupla1 = (1, 2, 3)
tupla2 = (4, 5, 6)
concatenacion = tupla1 + tupla2

print(concatenacion) # Output: (1, 2, 3, 4, 5, 6)

(1, 2, 3, 4, 5, 6)


En este ejemplo, creamos dos tuplas, `tupla1` y `tupla2`, que contienen tres elementos numéricos cada una. A continuación, utilizamos el operador de suma para concatenar las dos tuplas en una nueva tupla llamada `concatenacion`. Finalmente, imprimimos el valor de la tupla concatenada en la consola.

La repetición de tuplas en Python se realiza utilizando el operador de multiplicación `(*)`. Este operador toma una tupla y un entero y crea una nueva tupla que contiene múltiples copias de la tupla original. Veamos un ejemplo:

In [18]:
tupla1 = (1, 2, 3)
repeticion = tupla1 * 3

print(repeticion) # Output: (1, 2, 3, 1, 2, 3, 1, 2, 3)

(1, 2, 3, 1, 2, 3, 1, 2, 3)


En este ejemplo, creamos una tupla llamada `tupla1` que contiene tres elementos numéricos. Luego, utilizamos el operador de multiplicación para crear una nueva tupla llamada `repeticion` que contiene tres copias de la tupla original. Finalmente, imprimimos el valor de la tupla repetida en la consola.

Es importante destacar que la concatenación y repetición de tuplas crean nuevas tuplas en lugar de modificar las originales. Además, estas operaciones pueden combinarse para crear tuplas más complejas. Veamos un ejemplo:

In [19]:
tupla1 = (1, 2, 3)
tupla2 = (4, 5, 6)
repetida = (tupla1 + tupla2) * 2

print(repetida) # Output: (1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6)

(1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6)


En este ejemplo, creamos dos tuplas, `tupla1` y `tupla2`, que contienen tres elementos numéricos cada una. Luego, utilizamos el operador de suma para concatenar las dos tuplas en una nueva tupla. Después, utilizamos el operador de multiplicación para crear una nueva tupla que contiene dos copias de la tupla concatenada. Finalmente, imprimimos el valor de la tupla repetida en la consola.

En resumen, la concatenación y repetición de tuplas en Python son operaciones que permiten combinar o duplicar tuplas existentes para crear nuevas tuplas.

## **Tamaño de una tupla**

El tamaño de una tupla en Python se refiere al número de elementos que contiene una tupla. En otras palabras, es la longitud de la tupla. El tamaño de una tupla se puede obtener utilizando la función `len()`, que devuelve el número de elementos en la tupla. Veamos un ejemplo:

In [20]:
tupla = (1, 2, 3, 4, 5)
tamaño = len(tupla)

print(tamaño) # Output: 5

5


En este ejemplo, creamos una tupla llamada tupla que contiene cinco elementos numéricos. A continuación, utilizamos la función `len()` para obtener el tamaño de la tupla y lo asignamos a la variable tamaño. Finalmente, imprimimos el valor de la variable tamaño en la consola.

Es importante destacar que el tamaño de una tupla es inmutable, es decir, una vez que se crea una tupla, no se puede modificar su tamaño. Si se intenta modificar el tamaño de una tupla, se generará un error en tiempo de ejecución. Por ejemplo:

In [21]:
tupla = (1, 2, 3)
tupla.append(4) # Genera un error

AttributeError: 'tuple' object has no attribute 'append'

En este ejemplo, intentamos agregar un nuevo elemento a la tupla utilizando el método `append()`. Sin embargo, esto generará un error en tiempo de ejecución porque las tuplas son inmutables y su tamaño no puede ser modificado.

En resumen, el tamaño de una tupla en Python se refiere al número de elementos que contiene y se puede obtener utilizando la función `len()`. Es importante tener en cuenta que el tamaño de una tupla es inmutable y no se puede modificar una vez que se ha creado.

## **Bucles y tuplas**

En Python, los bucles son una estructura de control que permiten repetir un bloque de código varias veces hasta que se cumpla una condición. Las tuplas, por su parte, son estructuras de datos que permiten almacenar varios elementos de diferentes tipos en una sola variable. En este sentido, es posible utilizar las tuplas en combinación con los bucles para realizar operaciones repetitivas en una colección de elementos.

Existen dos tipos principales de bucles en Python: el bucle `for` y el bucle `while`. El bucle `for` es ideal para recorrer colecciones de elementos como las tuplas, mientras que el bucle `while` es útil cuando se desea repetir un bloque de código mientras se cumpla una determinada condición.

A continuación, se muestra un ejemplo de cómo se puede utilizar un bucle `for` para recorrer una tupla e imprimir cada uno de sus elementos:

In [22]:
tupla = (1, 2, 3, 4, 5)

for elemento in tupla:
    print(elemento)

1
2
3
4
5


En este ejemplo, creamos una tupla llamada tupla que contiene cinco elementos numéricos. A continuación, utilizamos un bucle `for` para recorrer la tupla e imprimir cada uno de sus elementos en la consola.

También es posible utilizar el bucle `while` para recorrer una tupla utilizando un índice. A continuación, se muestra un ejemplo de cómo se puede utilizar un bucle `while` para recorrer una tupla e imprimir cada uno de sus elementos utilizando un índice:

In [23]:
tupla = (1, 2, 3, 4, 5)
indice = 0

while indice < len(tupla):
    print(tupla[indice])
    indice += 1

1
2
3
4
5


En este ejemplo, creamos una tupla llamada tupla que contiene cinco elementos numéricos y una variable indice inicializada en cero. Utilizamos un bucle `while` para recorrer la tupla e imprimir cada uno de sus elementos utilizando un índice. En cada iteración del bucle, imprimimos el elemento de la tupla correspondiente al índice actual y luego incrementamos el índice en uno.

En resumen, es posible utilizar las tuplas en combinación con los bucles `for` o `while` para realizar operaciones repetitivas en una colección de elementos. Con el bucle `for`, podemos recorrer una tupla de forma sencilla, mientras que con el bucle `while` podemos utilizar un índice para recorrer la tupla.

## **Tuplas y el resto de estructuras de datos**

En Python, existen diversas estructuras de datos que se pueden utilizar para almacenar y manipular colecciones de elementos. Las tuplas son una de estas estructuras de datos, pero también existen listas, conjuntos y diccionarios.

Las listas son una estructura de datos similar a las tuplas, pero a diferencia de las tuplas, las listas son mutables, lo que significa que se pueden modificar sus elementos después de haber sido creadas. Las listas se crean utilizando corchetes (`[]`) y los elementos se separan por comas. A continuación, se muestra un ejemplo de cómo crear una lista:

In [26]:
lista = [1, 2, 3, 4, 5]
print(lista)

[1, 2, 3, 4, 5]


Los conjuntos son una estructura de datos que almacena elementos únicos en una colección. Los conjuntos se crean utilizando llaves (`{}`) o la función `set()`. A continuación, se muestra un ejemplo de cómo crear un conjunto:

In [27]:
conjunto = {1, 2, 3, 4, 5}
print(conjunto)

{1, 2, 3, 4, 5}


Los diccionarios son una estructura de datos que almacena pares de `clave-valor` en una colección. Los diccionarios se crean utilizando llaves (`{}`) y los pares de `clave-valor` se separan por comas y se separan las claves de los valores con dos puntos (`:`). A continuación, se muestra un ejemplo de cómo crear un diccionario:

In [28]:
diccionario = {"nombre": "Juan", "apellido": "Pérez", "edad": 30}
print(diccionario)

{'nombre': 'Juan', 'apellido': 'Pérez', 'edad': 30}


Aunque estas estructuras de datos tienen características y usos distintos, todas ellas se pueden utilizar en combinación con los bucles `for` o `while` para realizar operaciones repetitivas en una colección de elementos. A continuación, se muestra un ejemplo de cómo se puede utilizar un bucle `for` para recorrer una lista, un conjunto y un diccionario e imprimir sus elementos:

In [29]:
# Recorriendo una lista
lista = [1, 2, 3, 4, 5]
for elemento in lista:
    print(elemento)

# Recorriendo un conjunto
conjunto = {1, 2, 3, 4, 5}
for elemento in conjunto:
    print(elemento)

# Recorriendo un diccionario
diccionario = {"nombre": "Juan", "apellido": "Pérez", "edad": 30}
for clave, valor in diccionario.items():
    print(clave, valor)

1
2
3
4
5
1
2
3
4
5
nombre Juan
apellido Pérez
edad 30


En este ejemplo, utilizamos un bucle `for` para recorrer una lista, un conjunto y un diccionario e imprimir sus elementos. En el caso de la lista y el conjunto, utilizamos una sintaxis similar a la de la tupla para recorrer sus elementos. En el caso del diccionario, utilizamos el método `items()` para recorrer los pares de `clave-valor` y así imprimir tanto la clave como el valor en cada iteración del bucle.

En resumen, aunque las tuplas son una estructura de datos útil en Python, también existen otras estructuras de datos como las listas, los conjuntos y los diccionarios que se pueden utilizar para almacenar y manipular colecciones de elementos. Todas estas estructuras de datos se pueden utilizar en combinación con los bucles `for` o `while` para realizar operaciones repetitivas en una colección de elementos.

## **La función zip**

La función `zip` en Python es una función incorporada que permite combinar dos o más iterables en una tupla de tuplas, donde cada tupla contiene los elementos correspondientes de cada iterable. En otras palabras, `zip` toma dos o más iterables y devuelve un iterador que devuelve tuplas formadas por los elementos de cada iterable.

La sintaxis de la función `zip` es la siguiente:

```
zip(iterable1, iterable2, ...)
```

Donde `iterable1`, `iterable2`, etc. son los iterables que se van a combinar.

A continuación, se muestra un ejemplo de cómo se puede utilizar la función `zip` para combinar dos listas en una tupla de tuplas:

In [30]:
nombres = ["Juan", "María", "Pedro"]
edades = [25, 30, 35]

datos_personales = zip(nombres, edades)

print(list(datos_personales))

[('Juan', 25), ('María', 30), ('Pedro', 35)]


En este ejemplo, se definen dos listas `nombres` y `edades`. Luego, se utiliza la función `zip` para combinar las dos listas en una tupla de tuplas llamada `datos_personales`. Finalmente, se convierte el iterador `datos_personales` en una lista para poder imprimir su contenido.

Como se puede observar, la función `zip` ha combinado los elementos correspondientes de las dos listas y los ha agrupado en una tupla de tuplas.

Es importante destacar que si los iterables tienen longitudes diferentes, la función `zip` se detendrá cuando se hayan agotado los elementos del iterable más corto. Por ejemplo:

In [31]:
nombres = ["Juan", "María", "Pedro"]
edades = [25, 30]

datos_personales = zip(nombres, edades)

print(list(datos_personales))

[('Juan', 25), ('María', 30)]


En este caso, la lista edades es más corta que la lista nombres, por lo que la función `zip` solo combinará los dos primeros elementos de cada lista.

En resumen, la función `zip` en Python es una herramienta muy útil para combinar dos o más iterables en una tupla de tuplas. Esta función permite trabajar con varias colecciones de datos al mismo tiempo y puede ahorrar mucho tiempo y esfuerzo al escribir código.

## **Estructuras de datos: Tuplas**

En Python, las tuplas son una estructura de datos inmutable que permite almacenar una secuencia de valores. A diferencia de las listas, las tuplas no pueden modificarse una vez creadas, lo que las hace ideales para almacenar datos que no necesitan cambiar.

Las tuplas se crean utilizando paréntesis `()` y los elementos se separan por comas. Por ejemplo:

In [32]:
tupla1 = (1, 2, 3)
tupla2 = ('a', 'b', 'c')
tupla3 = (True, False, True)

En este ejemplo, se han creado tres tuplas diferentes. La `tupla1` contiene los valores enteros `1`, `2` y `3`. La `tupla2` contiene los valores de caracteres `'a'`, `'b'` y `'c'`. La `tupla3` contiene los valores booleanos `True`, `False` y `True`.

Al igual que con las listas, se puede acceder a los elementos de una tupla mediante un índice numérico. El primer elemento de la tupla tiene un índice de `0`, el segundo tiene un índice de `1`, y así sucesivamente. Por ejemplo:

In [33]:
tupla = ('a', 'b', 'c', 'd', 'e')

print(tupla[0])  # salida: 'a'
print(tupla[2])  # salida: 'c'
print(tupla[-1]) # salida: 'e'

a
c
e


En este ejemplo, se ha creado una tupla llamada `tupla` que contiene cinco valores de caracteres. Los valores se pueden acceder utilizando índices, como se muestra en los tres ejemplos de impresión.

Además de acceder a los elementos, las tuplas también admiten la concatenación y repetición mediante el uso de los operadores `"+"` y `"*"`. Por ejemplo:

In [34]:
tupla1 = (1, 2, 3)
tupla2 = ('a', 'b', 'c')

tupla_concatenada = tupla1 + tupla2
tupla_repetida = tupla1 * 3

print(tupla_concatenada) # salida: (1, 2, 3, 'a', 'b', 'c')
print(tupla_repetida)    # salida: (1, 2, 3, 1, 2, 3, 1, 2, 3)

(1, 2, 3, 'a', 'b', 'c')
(1, 2, 3, 1, 2, 3, 1, 2, 3)


En este ejemplo, se han creado dos tuplas, `tupla1` y `tupla2`, que se concatenan utilizando el operador `"+"`. El resultado se almacena en la variable `tupla_concatenada`. Luego, la tupla `tupla1` se repite tres veces utilizando el operador `"*"`. El resultado se almacena en la variable `tupla_repetida`.

Otra característica útil de las tuplas es el desempaquetado, que permite asignar cada elemento de una tupla a una variable separada. Por ejemplo:

In [35]:
tupla = ('Juan', 25, 'Estados Unidos')

nombre, edad, pais = tupla

print(nombre) # salida: 'Juan'
print(edad)   # salida: 25
print(pais)   # salida: 'Estados Unidos'

Juan
25
Estados Unidos


En este ejemplo, se ha creado una tupla `tupla` que contiene tres valores diferentes. Luego, los valores se asignan a las variables `nombre`, `edad` y `pais`.

## **Tuples**

Una tupla es una colección de diferentes tipos de datos ordenados e inmutables (inmutables). Las tuplas se escriben con corchetes, `()`. Una vez que se crea una tupla, no podemos cambiar sus valores. No podemos usar métodos de agregar, insertar, eliminar en una tupla porque no es modificable (mutable). A diferencia de list, tuple tiene pocos métodos. Métodos relacionados con las tuplas:

* **tuple():** para crear una tupla vacía
* **count ():** para contar el número de un elemento específico en una tupla
* **index ():** para encontrar el índice de un elemento específico en una tupla
* **operador:** unir dos o más tuplas y crear una nueva tupla

### **Creando una tupla**

* **Tupla vacía:** creación de una tupla vacía

In [36]:
# syntax
empty_tuple = ()
# o usando el constructor de tuplas
empty_tuple = tuple()

* Tupla con valores iniciales

In [37]:
# syntax
tpl = ('item1', 'item2','item3')

In [38]:
fruits = ('banana', 'orange', 'mango', 'lemon')

### **longitud de la tupla**

Usamos el método `len()` para obtener la longitud de una tupla.

In [39]:
# syntax
tpl = ('item1', 'item2', 'item3')
len(tpl)

3

### **Acceso a elementos de tupla**

* Indexación positiva Similar al tipo de datos de lista, usamos indexación positiva o negativa para acceder a elementos de tupla.

![Acceso](../imagenes%20Python/tuples_index.png "elementos de tupla")

In [40]:
# Syntax
tpl = ('item1', 'item2', 'item3')
first_item = tpl[0]
print(first_item)

second_item = tpl[1]
print(second_item)

item1
item2


In [41]:
fruits = ('banana', 'orange', 'mango', 'lemon')
first_fruit = fruits[0]
print(first_fruit)

second_fruit = fruits[1]
print(second_fruit)

last_index =len(fruits) - 1
print(last_index)

last_fruit = fruits[last_index]
print(last_fruit)

banana
orange
3
lemon


* **Indexación negativa:**

 La indexación negativa significa comenzar desde el final, `-1` se refiere al último elemento, `-2` se refiere al penúltimo y el negativo de la longitud de la lista/tupla se refiere al primer elemento.

![indexacion negativa](../imagenes%20Python/tuple_negative_indexing.png "indexacion negativa")

In [42]:
# Syntax
tpl = ('item1', 'item2', 'item3','item4')
first_item = tpl[-4]
print(first_item)

second_item = tpl[-3]
print(second_item)

item1
item2


In [43]:
fruits = ('banana', 'orange', 'mango', 'lemon')
first_fruit = fruits[-4]
print(first_fruit)

second_fruit = fruits[-3]
print(second_fruit)

last_fruit = fruits[-1]
print(last_fruit)

banana
orange
lemon


### **Slicing tuples**

Podemos dividir una `subtupla` especificando un rango de índices donde comenzar y donde terminar en la tupla, el valor devuelto será una nueva tupla con los elementos especificados.

* Rango de índices positivos

In [44]:
# Syntax
tpl = ('item1', 'item2', 'item3','item4')
all_items = tpl[0:4]         # todos los artículos
print(all_items)

all_items = tpl[0:]         # todos los artículos
print(all_items)

middle_two_items = tpl[1:3]  # no incluye artículo en index 3
print(middle_two_items)

('item1', 'item2', 'item3', 'item4')
('item1', 'item2', 'item3', 'item4')
('item2', 'item3')


In [45]:
fruits = ('banana', 'orange', 'mango', 'lemon')
all_fruits = fruits[0:4]    # todos los artículos
print(all_fruits)

all_fruits= fruits[0:]      # todos los artículos
print(all_fruits)

orange_mango = fruits[1:3]  # no incluye artículo en index 3
print(orange_mango)

orange_to_the_rest = fruits[1:]
print(orange_to_the_rest)

('banana', 'orange', 'mango', 'lemon')
('banana', 'orange', 'mango', 'lemon')
('orange', 'mango')
('orange', 'mango', 'lemon')


* Rango de índices negativos

In [46]:
# Syntax
tpl = ('item1', 'item2', 'item3','item4')
all_items = tpl[-4:]         # todos los artículos
print(all_items)

middle_two_items = tpl[-3:-1]  # no incluye artículo en index 3 (-1)
print(middle_two_items)

('item1', 'item2', 'item3', 'item4')
('item2', 'item3')


In [47]:
fruits = ('banana', 'orange', 'mango', 'lemon')
all_fruits = fruits[-4:]    # todos los artículos
print(all_fruits)

orange_mango = fruits[-3:-1]  # no incluye artículo en  index 3
print(orange_mango)

orange_to_the_rest = fruits[-3:]
print(orange_to_the_rest)

('banana', 'orange', 'mango', 'lemon')
('orange', 'mango')
('orange', 'mango', 'lemon')


### **Cambiar tuplas a listas**

Podemos cambiar tuplas por listas y listas por tuplas. Tupla es inmutable si queremos modificar una tupla debemos cambiarla a una lista.

In [48]:
# Syntax
tpl = ('item1', 'item2', 'item3','item4')
lst = list(tpl)
print(lst)

['item1', 'item2', 'item3', 'item4']


In [49]:
fruits = ('banana', 'orange', 'mango', 'lemon')
fruits = list(fruits)
print(fruits)

fruits[0] = 'apple'
print(fruits)     # ['apple', 'orange', 'mango', 'lemon']

fruits = tuple(fruits)
print(fruits)     # ('apple', 'orange', 'mango', 'lemon')

['banana', 'orange', 'mango', 'lemon']
['apple', 'orange', 'mango', 'lemon']
('apple', 'orange', 'mango', 'lemon')


### **Comprobación de un elemento en una tupla**

Podemos verificar si un elemento existe o no en una tupla usando `in` , devuelve un valor booleano.

In [50]:
# Syntax
tpl = ('item1', 'item2', 'item3','item4')
'item2' in tpl # True

True

In [51]:
fruits = ('banana', 'orange', 'mango', 'lemon')
print('orange' in fruits) # True
print('apple' in fruits) # False
#fruits[0] = 'apple' # TypeError: 'tuple' el objeto no admite la asignación de elementos

True
False


### **Unión de tuplas**

Podemos unir dos o más tuplas usando el operador `+`

In [52]:
# syntax
tpl1 = ('item1', 'item2', 'item3')
tpl2 = ('item4', 'item5','item6')
tpl3 = tpl1 + tpl2
print(tpl3)

('item1', 'item2', 'item3', 'item4', 'item5', 'item6')


In [53]:
fruits = ('banana', 'orange', 'mango', 'lemon')
vegetables = ('Tomato', 'Potato', 'Cabbage','Onion', 'Carrot')
fruits_and_vegetables = fruits + vegetables
print(fruits_and_vegetables)

('banana', 'orange', 'mango', 'lemon', 'Tomato', 'Potato', 'Cabbage', 'Onion', 'Carrot')


### **Eliminación de tuplas**

No es posible eliminar un solo elemento en una tupla, pero es posible eliminar la tupla en sí usando `del`

In [54]:
# syntax
tpl1 = ('item1', 'item2', 'item3')
del tpl1

In [55]:
fruits = ('banana', 'orange', 'mango', 'lemon')
del fruits

| **Inicio** | **atrás 8** | **Siguiente 10** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./8.Estructuras_de_datos_Conjuntos.ipynb)| [⏩](./10.Funciones_en_Python.ipynb)|